import os

# 在 Windows 上禁用 huggingface 的 xet 传输和 symlink 缓存，
# 避免下载时 401 错误和符号链接失败。
os.environ.setdefault("HF_HUB_DISABLE_XET", "1")
os.environ.setdefault("HF_HUB_DISABLE_SYMLINKS", "1")

from transformers import T5Tokenizer, T5ForConditionalGeneration

tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-base")
model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-base")
print(f"total params: {model.num_parameters()}")

email_text = """Hi,Thank you for using Bosch Mobility Aftermarket Claim Management Portal (CMP).This email is to remind you that a new claim # MAAO-0000001771 has been assigned under your role as in the approval workflow. Please don’t forget to log onto CMP and complete approval procedure, or simply use following link. https://ap-claims-bosch-q.cfapps.ap11.hana.ondemand.com/index.html#/AU/workflow/2074038110617993216 Claim Summary Claim Number MAAO-0000001771Customer Reference Number Submitted Time 17:49 06-07-2026Customer Name O'BRIEN GLASS INDUSTRIES LTDSold To Party 0191308972Submitted By qix8szhClaim Type Price DiscrepancyClaim Category Freight(Note: Please do not reply to this email since it is automatically generated by the system, thank you.)Best regards,Bosch Mobility Aftermarket Claim Management Portal Ocenia"""

fields = ["Claim Number", "Customer Name", "Sold To Party"]

# 每个字段单独提问，避免多字段同时生成时相互干扰
for field in fields:
    input_text = f"""Email: {email_text}

What is the {field}? Answer with the value only."""
    input_ids = tokenizer(input_text, return_tensors="pt").input_ids

    outputs = model.generate(
        input_ids,
        max_new_tokens=20,
        num_beams=4,
        early_stopping=True,
        do_sample=False,
    )
    print(f"{field}: {tokenizer.decode(outputs[0], skip_special_tokens=True)}")
